### PR TITLE
Support react-redux

### PR DESCRIPTION
**Pull request by dancerphil**
You've done a great job. If we support react-redux, the package can be widely used.

### CODE REVIEW

**Comment by Flavien-Pensato** [comment]
Maybe we can add redux as optional. Because the goal was (I guess) to not use redux ?

**Comment by flepretre** [comment]
The idea was more to replace it, not to depends on it. But you're right, it will be easier to use, and I don't need to finish the full implementation of connect anymore 😅 

If we do so, please remove the connect implementation.

**Comment by dancerphil** [comment]
I guess we are not going to install `react-redux` as a peerDependencies.

But if developer installed `react-redux@5`, it will break.

Maybe it should be written in docs if we decided to apply this.

**Comment by flepretre** [comment]
Maybe if we do not provide `react-redux` stuff but just the hook, then we could set `react-redux` as peer and force version >= 6 🤔

**Comment by flepretre** [comment]
Close #1

**Comment by flepretre** [comment]
All things considered we'll do like this. I'll update the doc.

Thanks for your contribution 👍

**Pull request merged**
